### ISSUE TITLE
Days/Hours/Minutes in survivaltime placeholders (and fix stories menu)

### ISSUE THREAD

**Issue by cafestifflered** [GamerSafer/ablockalypse#10]
Currently showing hundreds of minutes. Switch to showing hours in the placeholder and the stories menu.

Fix survivaltime ticking while player is offline

![image](https://user-images.githubusercontent.com/73274299/184667202-75f8bc6a-986c-4b28-9fbd-806c0565031f.png)

**Comment by SpaicyGaming** [comment]
The duration format is configurable in the config.yml at "format.duration".
Currently, it's set to "d 'days', HH 'hours', mm 'minutes'". 
These are the duration formatter docs: https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/time/DurationFormatUtils.html
