### ISSUE TITLE
Remove TagAPI dependency

### ISSUE THREAD

**Issue by cafestifflered** [GamerSafer/ablockalypse#25]
I don't believe that TagAPI is currently being used for anything on account of the Thief backstory not yet being accessible. It pops up in timings and spark profilers for lag cause, which is a severe issue on the server right now.

If it's possible, please remove the need for TagAPI so I can uninstall that plugin and see if that helps performance at all.

https://timings.aikar.co/dev/?id=c5d5f0cd8ed14c6a9bd0b821459c2301#timings
https://spark.lucko.me/tHSG2B8vMV

**Comment by SpaicyGaming** [comment]
The no-tags branch, the one currently used in production, doesn't depend on TagAPI. That plugin can be uninstalled
