### ISSUE TITLE
Remove tab-autocomplete of safehouse names for normal players

### ISSUE THREAD

**Issue by cafestifflered** [GamerSafer/ablockalypse#34]
The list is so long it's become unusable for regular players. Remove all the safehouse names from autocomplete and just leave the usable commands (boosters, door, etc...)

If possible, let admins with a certain permission keep seeing all the safehouse names for autocomplete, but the main thing is removing it for all other players.

![image](https://user-images.githubusercontent.com/73274299/207489984-4b976022-50c7-457e-b690-1a85ed5ad442.png)

**Comment by michelecoco** [comment]
Suggestions will be displayed only to players who have the `ablockalypse.cmd.safehouse` permission
