### ISSUE TITLE
Safehouse door upgrades

### ISSUE THREAD

**Issue by OmegaMinecraft** [GamerSafer/ablockalypse#42]
Edit the wording so it shows the complete amounts needed.
1st upgrade - 5 Planks and 5 Sheet Metal
2nd upgrade - 8 Planks and 8 Sheet Metal

**Comment by cafestifflered** [comment]
Fixed in https://github.com/GamerSafer/ablockalypse/commit/a55eac7bf273c5640260485595b1448875ced135
