### ISSUE TITLE
Hospital locations are acting as spawnpoint locations

### ISSUE THREAD

**Issue by cafestifflered** [GamerSafer/ablockalypse#5]
After a player dies, they sometimes get spawned at a random hospital location. There is only one set spawnpoint, however, and so they should always be respawned back at that spawnpoint.

I believe that the respawn mechanic is looping through the hospital locations as valid spawnpoints, even though they are not.

Double check as well that the hospital spawning mechanic isn't utilizing the spawnpoints as valid hospital location. This would be bad if a player chose their story and then respawned at the spawnpoint.

**Comment by cafestifflered** [comment]
Pretty sure I fixed this in https://github.com/GamerSafer/ablockalypse/commit/3d169d5458428f1d2c0ff86b951b7e49b45c1d0c

Please review to make sure before closing

**Comment by SpaicyGaming** [comment]
Looks good to me. Good catch!
